export type OutcomeDataEntry = {
  successRate: number;
  caseCount: number;
};

export type TherapistAccountSeed = {
  name: string;
  providerType: "mental-health" | "physical-therapy";
  networkSource: string;
  email?: string;
  accessCode?: string;
  title: string;
  location: string;
  bio: string;
  languages: string[];
  modalities: string[];
  careFormats: string[];
  licensedStates: string[];
  availability: {
    summary: string;
    nextOpenSlot?: string | null;
  };
  profileAttributes?: Record<string, unknown>;
  specialties: string[];
  outcomeData: Record<string, OutcomeDataEntry>;
};

export const therapistRoster: TherapistAccountSeed[] = [
  {
    name: "Dr. Evelyn Hart",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    email: "evelyn.hart@anamnesis.demo",
    accessCode: "HART-2048",
    title: "Trauma Therapist, LMFT",
    location: "Austin, Texas",
    bio: "Grounded, gently structured trauma work for clients who have spent years living in survival mode.",
    languages: ["English", "Spanish"],
    modalities: ["EMDR", "parts work", "somatic grounding"],
    careFormats: ["virtual", "video"],
    licensedStates: ["TX", "CO", "CA"],
    availability: {
      summary: "Opens 2 new trauma-focused consult slots this week",
      nextOpenSlot: "2026-04-21T14:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "young-adults"],
      traumaInformed: true,
      intakeStyle: "gentle-structured",
    },
    specialties: ["trauma", "ptsd", "complex-ptsd", "dissociation", "hypervigilance"],
    outcomeData: {
      "complex-ptsd": { successRate: 92, caseCount: 118 },
      ptsd: { successRate: 87, caseCount: 142 },
      anxiety: { successRate: 74, caseCount: 66 },
      depression: { successRate: 69, caseCount: 44 },
    },
  },
  {
    name: "Dr. Marcus Webb",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    email: "marcus.webb@anamnesis.demo",
    accessCode: "WEBB-3391",
    title: "Clinical Psychologist, Psy.D",
    location: "Chicago, Illinois",
    bio: "Evidence-based OCD and anxiety treatment using ERP and ACT for clients who want to reclaim their lives from compulsions and avoidance.",
    languages: ["English"],
    modalities: ["ERP", "ACT", "CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["IL", "WI", "IN"],
    availability: {
      summary: "Accepting new OCD and anxiety clients",
      nextOpenSlot: "2026-04-22T10:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "adolescents"],
      specialization: "OCD-spectrum",
    },
    specialties: ["ocd", "anxiety", "panic-disorder", "health-anxiety", "perfectionism"],
    outcomeData: {
      ocd: { successRate: 89, caseCount: 203 },
      anxiety: { successRate: 85, caseCount: 178 },
      "panic-disorder": { successRate: 82, caseCount: 94 },
      "health-anxiety": { successRate: 79, caseCount: 67 },
    },
  },
  {
    name: "Dr. Priya Nair",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    email: "priya.nair@anamnesis.demo",
    accessCode: "NAIR-7722",
    title: "Licensed Psychologist, Ph.D",
    location: "San Francisco, California",
    bio: "Specializing in depression, burnout, and life transitions for high-achieving professionals navigating identity and meaning.",
    languages: ["English", "Hindi", "Malayalam"],
    modalities: ["psychodynamic", "ACT", "CBT"],
    careFormats: ["virtual", "video"],
    licensedStates: ["CA", "NY", "WA"],
    availability: {
      summary: "Limited availability — 1 opening for new clients this month",
      nextOpenSlot: "2026-04-28T11:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "professionals"],
      culturalCompetency: ["South Asian", "immigrant experiences"],
    },
    specialties: ["depression", "burnout", "life-transitions", "identity", "grief"],
    outcomeData: {
      depression: { successRate: 88, caseCount: 156 },
      burnout: { successRate: 91, caseCount: 112 },
      "life-transitions": { successRate: 85, caseCount: 89 },
      grief: { successRate: 80, caseCount: 71 },
    },
  },
  {
    name: "Jordan Ellis, LCSW",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    email: "jordan.ellis@anamnesis.demo",
    accessCode: "ELLI-5512",
    title: "Licensed Clinical Social Worker",
    location: "New York, New York",
    bio: "Specialized in relational therapy, attachment wounds, and identity development. Works with adults and couples navigating life transitions, self-concept challenges, and interpersonal patterns.",
    languages: ["English", "French"],
    modalities: ["attachment-based", "IFS", "narrative therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["NY", "NJ", "CT"],
    availability: {
      summary: "Open to new clients",
      nextOpenSlot: "2026-04-20T15:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "young-adults", "couples"],
    },
    specialties: ["relationship-issues", "identity", "attachment", "anxiety", "life-transitions"],
    outcomeData: {
      "relationship-issues": { successRate: 86, caseCount: 134 },
      identity: { successRate: 90, caseCount: 97 },
      attachment: { successRate: 83, caseCount: 88 },
      "life-transitions": { successRate: 88, caseCount: 71 },
    },
  },
  {
    name: "Dr. Samuel Okafor",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    email: "samuel.okafor@anamnesis.demo",
    accessCode: "OKAF-9910",
    title: "Psychiatrist, MD",
    location: "Atlanta, Georgia",
    bio: "Integrative psychiatry combining medication management with therapy-informed care for treatment-resistant depression and bipolar disorder.",
    languages: ["English", "Yoruba"],
    modalities: ["integrative psychiatry", "psychoeducation", "CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["GA", "FL", "NC"],
    availability: {
      summary: "Accepting new psychiatric evaluations",
      nextOpenSlot: "2026-04-23T09:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      culturalCompetency: ["African diaspora", "Black mental health"],
      prescribes: true,
    },
    specialties: ["depression", "bipolar-disorder", "treatment-resistant-depression", "anxiety"],
    outcomeData: {
      depression: { successRate: 84, caseCount: 221 },
      "bipolar-disorder": { successRate: 79, caseCount: 143 },
      "treatment-resistant-depression": { successRate: 71, caseCount: 88 },
      anxiety: { successRate: 78, caseCount: 112 },
    },
  },
  {
    name: "Wei Chen, LMFT",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    email: "wei.chen@anamnesis.demo",
    accessCode: "CHEN-4481",
    title: "Licensed Marriage and Family Therapist",
    location: "Los Angeles, California",
    bio: "Culturally responsive therapy for individuals and couples navigating immigration stress, family dynamics, and intergenerational trauma.",
    languages: ["English", "Mandarin", "Cantonese"],
    modalities: ["narrative therapy", "family systems", "somatic"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["CA"],
    availability: {
      summary: "Open slots — bilingual sessions available",
      nextOpenSlot: "2026-04-21T13:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "couples", "families"],
      culturalCompetency: ["East Asian", "Chinese diaspora", "immigrant"],
    },
    specialties: ["relationship-issues", "family-conflict", "immigration-stress", "anxiety", "complex-ptsd"],
    outcomeData: {
      "relationship-issues": { successRate: 87, caseCount: 162 },
      "family-conflict": { successRate: 84, caseCount: 119 },
      "immigration-stress": { successRate: 89, caseCount: 77 },
      anxiety: { successRate: 81, caseCount: 103 },
    },
  },
  {
    name: "Dr. Fatima Al-Rashid",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    email: "fatima.alrashid@anamnesis.demo",
    accessCode: "ALRA-6630",
    title: "Clinical Psychologist, Psy.D",
    location: "Houston, Texas",
    bio: "Trauma-informed grief therapy for bereaved clients, including sudden loss, disenfranchised grief, and prolonged grief disorder.",
    languages: ["English", "Arabic"],
    modalities: ["EMDR", "prolonged grief therapy", "mindfulness-based"],
    careFormats: ["virtual", "video"],
    licensedStates: ["TX", "OK", "LA"],
    availability: {
      summary: "Open to new grief and trauma clients",
      nextOpenSlot: "2026-04-22T14:30:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "elderly"],
      culturalCompetency: ["Arab diaspora", "Muslim-affirming"],
    },
    specialties: ["grief", "bereavement", "complex-grief", "trauma", "depression"],
    outcomeData: {
      grief: { successRate: 91, caseCount: 144 },
      bereavement: { successRate: 88, caseCount: 103 },
      "complex-grief": { successRate: 85, caseCount: 79 },
      trauma: { successRate: 80, caseCount: 67 },
      depression: { successRate: 76, caseCount: 55 },
    },
  },
  {
    name: "Alicia Moreno, LPC",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    email: "alicia.moreno@anamnesis.demo",
    accessCode: "MORE-2267",
    title: "Licensed Professional Counselor",
    location: "Phoenix, Arizona",
    bio: "Specializing in eating disorders and body image with a Health at Every Size approach.",
    languages: ["English", "Spanish"],
    modalities: ["DBT", "CBT-E", "motivational interviewing"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["AZ", "NM", "NV"],
    availability: {
      summary: "Accepting new eating disorder clients — HAES-aligned practice",
      nextOpenSlot: "2026-04-24T10:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "adolescents"],
      specialization: "eating-disorders",
      haes: true,
    },
    specialties: ["eating-disorders", "body-image", "anxiety", "depression", "self-esteem"],
    outcomeData: {
      "eating-disorders": { successRate: 82, caseCount: 131 },
      "body-image": { successRate: 86, caseCount: 109 },
      anxiety: { successRate: 78, caseCount: 88 },
      depression: { successRate: 75, caseCount: 71 },
    },
  },
  {
    name: "Dr. James Thornton",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    email: "james.thornton@anamnesis.demo",
    accessCode: "THOR-8821",
    title: "Addiction Psychiatrist, MD",
    location: "Seattle, Washington",
    bio: "Board-certified addiction medicine with integrated psychiatric care for substance use, co-occurring disorders, and recovery maintenance.",
    languages: ["English"],
    modalities: ["MAT", "motivational interviewing", "CBT", "12-step facilitation"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["WA", "OR", "ID"],
    availability: {
      summary: "Accepting new addiction medicine evaluations",
      nextOpenSlot: "2026-04-25T09:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      prescribes: true,
      specialization: "addiction-medicine",
    },
    specialties: ["addiction", "substance-use", "alcohol-use-disorder", "opioid-use-disorder", "co-occurring"],
    outcomeData: {
      addiction: { successRate: 76, caseCount: 198 },
      "substance-use": { successRate: 74, caseCount: 167 },
      "alcohol-use-disorder": { successRate: 78, caseCount: 134 },
      "opioid-use-disorder": { successRate: 71, caseCount: 88 },
    },
  },
  {
    name: "Sofia Reyes, LCSW",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    email: "sofia.reyes@anamnesis.demo",
    accessCode: "REYE-3344",
    title: "Perinatal Mental Health Specialist, LCSW",
    location: "Miami, Florida",
    bio: "Supporting individuals through pregnancy, postpartum, and infant loss with compassionate, evidence-based perinatal mental health care.",
    languages: ["English", "Spanish"],
    modalities: ["CBT", "interpersonal therapy", "supportive therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["FL", "TX", "NY"],
    availability: {
      summary: "Open to perinatal clients — evening slots available",
      nextOpenSlot: "2026-04-21T18:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "perinatal"],
      specialization: "perinatal-mental-health",
      pmhc: true,
    },
    specialties: ["postpartum-depression", "pregnancy-anxiety", "infant-loss", "depression", "anxiety"],
    outcomeData: {
      "postpartum-depression": { successRate: 90, caseCount: 143 },
      "pregnancy-anxiety": { successRate: 87, caseCount: 98 },
      "infant-loss": { successRate: 84, caseCount: 56 },
      depression: { successRate: 82, caseCount: 88 },
      anxiety: { successRate: 80, caseCount: 74 },
    },
  },
  {
    name: "Dr. Kevin Park",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    email: "kevin.park@anamnesis.demo",
    accessCode: "PARK-6655",
    title: "ADHD Specialist, Ph.D",
    location: "Boston, Massachusetts",
    bio: "Neuropsychology-informed ADHD assessment and treatment for adults who were diagnosed late or are learning to work with their brain.",
    languages: ["English", "Korean"],
    modalities: ["CBT for ADHD", "skills coaching", "psychoeducation"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["MA", "NH", "VT"],
    availability: {
      summary: "Open for ADHD assessments and therapy",
      nextOpenSlot: "2026-04-26T11:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "young-adults"],
      specialization: "adhd",
      assessments: true,
    },
    specialties: ["adhd", "executive-dysfunction", "anxiety", "depression", "procrastination"],
    outcomeData: {
      adhd: { successRate: 85, caseCount: 219 },
      "executive-dysfunction": { successRate: 82, caseCount: 156 },
      anxiety: { successRate: 78, caseCount: 99 },
      depression: { successRate: 74, caseCount: 77 },
    },
  },
  {
    name: "Maya Johnson, MFT",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    email: "maya.johnson@anamnesis.demo",
    accessCode: "JOHN-9987",
    title: "Marriage and Family Therapist",
    location: "Denver, Colorado",
    bio: "Warm, direct therapy for anxiety, life transitions, and relationship issues with a focus on building resilience and self-trust.",
    languages: ["English"],
    modalities: ["CBT", "solution-focused", "mindfulness-based"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["CO", "WY", "NM"],
    availability: {
      summary: "Multiple openings this week",
      nextOpenSlot: "2026-04-20T14:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "young-adults"],
    },
    specialties: ["anxiety", "life-transitions", "relationship-issues", "self-esteem", "stress"],
    outcomeData: {
      anxiety: { successRate: 83, caseCount: 187 },
      "life-transitions": { successRate: 88, caseCount: 134 },
      "relationship-issues": { successRate: 80, caseCount: 112 },
      "self-esteem": { successRate: 85, caseCount: 91 },
    },
  },
  // ─── Additional 43 profiles ─────────────────────────────────────────────────
  {
    name: "Dr. Camille Rousseau",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Psychologist, Ph.D",
    location: "New Orleans, Louisiana",
    bio: "Depth-oriented trauma therapy with a focus on moral injury, survivor guilt, and the long tail of unprocessed grief.",
    languages: ["English", "French"],
    modalities: ["psychodynamic", "EMDR", "trauma-focused CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["LA", "MS", "AR"],
    availability: {
      summary: "Accepting complex trauma referrals",
      nextOpenSlot: "2026-04-23T13:00:00.000Z",
    },
    profileAttributes: { populations: ["adults", "veterans"], traumaInformed: true },
    specialties: ["complex-ptsd", "moral-injury", "grief", "depression", "trauma"],
    outcomeData: {
      "complex-ptsd": { successRate: 88, caseCount: 97 },
      "moral-injury": { successRate: 84, caseCount: 61 },
      grief: { successRate: 82, caseCount: 74 },
      depression: { successRate: 77, caseCount: 88 },
    },
  },
  {
    name: "Tariq Hassan, LPC",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Professional Counselor",
    location: "Minneapolis, Minnesota",
    bio: "Integrative counseling for anxiety, depression, and identity for Black and Muslim clients who want a culturally grounded therapeutic relationship.",
    languages: ["English", "Arabic", "Somali"],
    modalities: ["CBT", "ACT", "culturally-adapted therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["MN", "WI", "IA"],
    availability: {
      summary: "Open to new clients — multilingual sessions available",
      nextOpenSlot: "2026-04-22T09:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "young-adults"],
      culturalCompetency: ["Black mental health", "Muslim-affirming", "East African diaspora"],
    },
    specialties: ["anxiety", "depression", "identity", "immigration-stress", "burnout"],
    outcomeData: {
      anxiety: { successRate: 84, caseCount: 122 },
      depression: { successRate: 81, caseCount: 108 },
      identity: { successRate: 88, caseCount: 74 },
      "immigration-stress": { successRate: 86, caseCount: 55 },
    },
  },
  {
    name: "Dr. Rebecca Hoffman",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Psychologist, Psy.D",
    location: "Portland, Oregon",
    bio: "Cognitive-behavioral and acceptance-based therapy for perfectionism, chronic worry, and high-functioning anxiety in adults.",
    languages: ["English"],
    modalities: ["CBT", "ACT", "metacognitive therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["OR", "WA", "CA"],
    availability: {
      summary: "Two openings for new anxiety clients",
      nextOpenSlot: "2026-04-21T10:00:00.000Z",
    },
    profileAttributes: { populations: ["adults", "professionals"], specialization: "anxiety" },
    specialties: ["anxiety", "perfectionism", "panic-disorder", "ocd", "burnout"],
    outcomeData: {
      anxiety: { successRate: 90, caseCount: 201 },
      perfectionism: { successRate: 87, caseCount: 133 },
      "panic-disorder": { successRate: 84, caseCount: 99 },
      burnout: { successRate: 80, caseCount: 88 },
    },
  },
  {
    name: "Naomi Williams, LMFT",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Marriage and Family Therapist",
    location: "Oakland, California",
    bio: "Somatic and attachment-based therapy for LGBTQ+ individuals navigating identity, family rejection, minority stress, and relationship repair.",
    languages: ["English"],
    modalities: ["somatic experiencing", "attachment-based", "affirmative therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["CA", "NV", "OR"],
    availability: {
      summary: "Open to LGBTQ+ individuals and couples",
      nextOpenSlot: "2026-04-22T14:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "young-adults", "LGBTQ+"],
      lgbtqAffirming: true,
    },
    specialties: ["identity", "lgbtq", "anxiety", "relationship-issues", "trauma"],
    outcomeData: {
      lgbtq: { successRate: 91, caseCount: 148 },
      identity: { successRate: 89, caseCount: 122 },
      anxiety: { successRate: 82, caseCount: 104 },
      "relationship-issues": { successRate: 85, caseCount: 77 },
    },
  },
  {
    name: "Dr. Luis Vargas",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Psychologist, Ph.D",
    location: "San Antonio, Texas",
    bio: "Trauma-informed care for Latino/a/x clients navigating familismo, machismo, and the intersection of cultural identity and mental health.",
    languages: ["English", "Spanish"],
    modalities: ["culturally-adapted CBT", "narrative therapy", "EMDR"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["TX", "NM", "CO"],
    availability: {
      summary: "Accepting bilingual Spanish-English clients",
      nextOpenSlot: "2026-04-23T10:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "families"],
      culturalCompetency: ["Latinx", "bicultural"],
    },
    specialties: ["trauma", "depression", "anxiety", "identity", "family-conflict"],
    outcomeData: {
      trauma: { successRate: 83, caseCount: 111 },
      depression: { successRate: 86, caseCount: 143 },
      identity: { successRate: 88, caseCount: 87 },
      "family-conflict": { successRate: 80, caseCount: 68 },
    },
  },
  {
    name: "Dr. Ananya Krishnamurthy",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Psychiatrist, MD",
    location: "San Jose, California",
    bio: "Precision psychiatry using genetic and biometric data to optimize medication protocols for treatment-resistant depression and bipolar disorder.",
    languages: ["English", "Tamil", "Hindi"],
    modalities: ["precision psychiatry", "psychoeducation", "integrative treatment"],
    careFormats: ["virtual"],
    licensedStates: ["CA", "WA"],
    availability: {
      summary: "Accepting psychiatric evaluation referrals",
      nextOpenSlot: "2026-04-29T11:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      prescribes: true,
      culturalCompetency: ["South Asian"],
    },
    specialties: ["depression", "bipolar-disorder", "treatment-resistant-depression", "anxiety"],
    outcomeData: {
      depression: { successRate: 87, caseCount: 178 },
      "bipolar-disorder": { successRate: 81, caseCount: 122 },
      "treatment-resistant-depression": { successRate: 75, caseCount: 91 },
    },
  },
  {
    name: "Owen MacAllister, LCSW",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Clinical Social Worker",
    location: "Nashville, Tennessee",
    bio: "Grief-focused therapy for adults navigating sudden loss, ambiguous loss, and caregiver grief. Specializes in clinical bereavement support.",
    languages: ["English"],
    modalities: ["prolonged grief therapy", "meaning-centered therapy", "CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["TN", "KY", "AL"],
    availability: {
      summary: "Open for grief and bereavement clients",
      nextOpenSlot: "2026-04-24T15:00:00.000Z",
    },
    profileAttributes: { populations: ["adults", "elderly"] },
    specialties: ["grief", "bereavement", "complex-grief", "depression", "life-transitions"],
    outcomeData: {
      grief: { successRate: 89, caseCount: 162 },
      bereavement: { successRate: 86, caseCount: 134 },
      "complex-grief": { successRate: 83, caseCount: 88 },
      depression: { successRate: 79, caseCount: 71 },
    },
  },
  {
    name: "Isabelle Fontaine, LMFT",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Couples and Family Therapist, LMFT",
    location: "Washington, D.C.",
    bio: "Emotionally Focused Therapy (EFT) for couples navigating attachment disruptions, infidelity recovery, and communication breakdown.",
    languages: ["English", "French"],
    modalities: ["EFT", "Gottman Method", "attachment-based"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["DC", "VA", "MD"],
    availability: {
      summary: "Open for couples therapy — two evening slots available",
      nextOpenSlot: "2026-04-21T19:00:00.000Z",
    },
    profileAttributes: { populations: ["couples", "adults"] },
    specialties: ["relationship-issues", "attachment", "communication", "infidelity-recovery", "anxiety"],
    outcomeData: {
      "relationship-issues": { successRate: 88, caseCount: 193 },
      attachment: { successRate: 85, caseCount: 144 },
      "infidelity-recovery": { successRate: 76, caseCount: 67 },
    },
  },
  {
    name: "Dr. David Chen",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Psychologist, Ph.D",
    location: "Philadelphia, Pennsylvania",
    bio: "Cognitive therapy for depression and dysthymia, with a particular focus on ruminative thinking, anhedonia, and returning to meaningful engagement.",
    languages: ["English", "Mandarin"],
    modalities: ["CBT", "behavioral activation", "mindfulness-based cognitive therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["PA", "NJ", "DE"],
    availability: {
      summary: "Accepting new depression referrals",
      nextOpenSlot: "2026-04-22T11:00:00.000Z",
    },
    profileAttributes: { populations: ["adults", "young-adults"] },
    specialties: ["depression", "dysthymia", "anxiety", "burnout", "life-transitions"],
    outcomeData: {
      depression: { successRate: 89, caseCount: 234 },
      dysthymia: { successRate: 85, caseCount: 112 },
      anxiety: { successRate: 81, caseCount: 144 },
      burnout: { successRate: 77, caseCount: 88 },
    },
  },
  {
    name: "Keiko Tanaka, LCSW",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Clinical Social Worker",
    location: "Honolulu, Hawaii",
    bio: "Mindfulness-based somatic therapy for anxiety and trauma. Fluent in Japanese and committed to bridging Eastern and Western wellness traditions.",
    languages: ["English", "Japanese"],
    modalities: ["somatic experiencing", "mindfulness-based stress reduction", "CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["HI", "CA"],
    availability: {
      summary: "Open to new clients — remote sessions across all time zones",
      nextOpenSlot: "2026-04-23T09:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      culturalCompetency: ["Japanese diaspora", "East Asian"],
    },
    specialties: ["anxiety", "trauma", "stress", "burnout", "depression"],
    outcomeData: {
      anxiety: { successRate: 86, caseCount: 142 },
      trauma: { successRate: 83, caseCount: 98 },
      stress: { successRate: 88, caseCount: 121 },
      burnout: { successRate: 84, caseCount: 97 },
    },
  },
  {
    name: "Dr. Reginald Brooks",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Psychologist, Psy.D",
    location: "Detroit, Michigan",
    bio: "Community-focused mental health for Black men navigating depression, trauma, and emotional suppression in high-pressure environments.",
    languages: ["English"],
    modalities: ["CBT", "culturally-adapted therapy", "narrative therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["MI", "OH", "IN"],
    availability: {
      summary: "Open to new clients — affirming space for Black men",
      nextOpenSlot: "2026-04-22T16:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      culturalCompetency: ["Black mental health"],
    },
    specialties: ["depression", "trauma", "anxiety", "identity", "stress"],
    outcomeData: {
      depression: { successRate: 87, caseCount: 167 },
      trauma: { successRate: 82, caseCount: 109 },
      anxiety: { successRate: 84, caseCount: 134 },
      identity: { successRate: 86, caseCount: 88 },
    },
  },
  {
    name: "Dr. Leila Mohammadi",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Psychologist, Ph.D",
    location: "Toronto, Ontario",
    bio: "Cross-cultural psychotherapy for Middle Eastern and Iranian clients navigating intergenerational family systems, displacement, and cultural identity.",
    languages: ["English", "Farsi", "Arabic"],
    modalities: ["psychodynamic", "CBT", "culturally-adapted therapy"],
    careFormats: ["virtual"],
    licensedStates: ["CA", "NY"],
    availability: {
      summary: "Accepting virtual clients — bilingual Farsi/English",
      nextOpenSlot: "2026-04-25T14:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      culturalCompetency: ["Iranian diaspora", "Middle Eastern", "Muslim-affirming"],
    },
    specialties: ["anxiety", "depression", "identity", "immigration-stress", "family-conflict"],
    outcomeData: {
      anxiety: { successRate: 85, caseCount: 114 },
      depression: { successRate: 83, caseCount: 97 },
      identity: { successRate: 89, caseCount: 78 },
      "immigration-stress": { successRate: 87, caseCount: 61 },
    },
  },
  {
    name: "Marcus Reid, LPC",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Professional Counselor",
    location: "Charlotte, North Carolina",
    bio: "Performance-focused burnout recovery and executive stress for professionals, athletes, and leaders who can't afford to slow down but need to.",
    languages: ["English"],
    modalities: ["CBT", "ACT", "solution-focused", "mindfulness-based"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["NC", "SC", "VA"],
    availability: {
      summary: "Specializes in professional burnout — openings available",
      nextOpenSlot: "2026-04-22T07:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "professionals", "athletes"],
    },
    specialties: ["burnout", "stress", "anxiety", "depression", "life-transitions"],
    outcomeData: {
      burnout: { successRate: 88, caseCount: 176 },
      stress: { successRate: 90, caseCount: 188 },
      anxiety: { successRate: 82, caseCount: 144 },
      depression: { successRate: 79, caseCount: 112 },
    },
  },
  {
    name: "Dr. Yuki Watanabe",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Eating Disorder Specialist, Psy.D",
    location: "Seattle, Washington",
    bio: "Specialized in anorexia nervosa, ARFID, and binge-eating disorder. Uses a weight-neutral, collaborative approach with medical team coordination when needed.",
    languages: ["English", "Japanese"],
    modalities: ["CBT-E", "DBT", "family-based treatment"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["WA", "OR"],
    availability: {
      summary: "Accepting eating disorder referrals",
      nextOpenSlot: "2026-04-26T10:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "adolescents"],
      specialization: "eating-disorders",
      medicalCoordination: true,
    },
    specialties: ["eating-disorders", "anorexia", "binge-eating", "body-image", "anxiety"],
    outcomeData: {
      "eating-disorders": { successRate: 84, caseCount: 148 },
      anorexia: { successRate: 78, caseCount: 77 },
      "binge-eating": { successRate: 86, caseCount: 99 },
      "body-image": { successRate: 83, caseCount: 118 },
    },
  },
  {
    name: "Simone Okonkwo, LCSW",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Clinical Social Worker",
    location: "Chicago, Illinois",
    bio: "Warm, direct therapy for women navigating postpartum depression, perinatal loss, and the identity shifts of new parenthood.",
    languages: ["English"],
    modalities: ["IPT", "CBT", "supportive therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["IL", "WI"],
    availability: {
      summary: "Open to perinatal mental health clients",
      nextOpenSlot: "2026-04-22T15:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "perinatal"],
      specialization: "perinatal-mental-health",
    },
    specialties: ["postpartum-depression", "anxiety", "grief", "identity", "depression"],
    outcomeData: {
      "postpartum-depression": { successRate: 91, caseCount: 127 },
      anxiety: { successRate: 85, caseCount: 104 },
      grief: { successRate: 82, caseCount: 67 },
      depression: { successRate: 84, caseCount: 99 },
    },
  },
  {
    name: "Dr. Aaron Goldstein",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Addiction Psychologist, Ph.D",
    location: "San Francisco, California",
    bio: "Harm reduction-informed addiction treatment integrating motivational interviewing, CBT, and community support for alcohol and stimulant use disorders.",
    languages: ["English"],
    modalities: ["harm reduction", "motivational interviewing", "CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["CA", "NV"],
    availability: {
      summary: "Accepting addiction and dual-diagnosis clients",
      nextOpenSlot: "2026-04-23T11:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      specialization: "addiction",
      harmReduction: true,
    },
    specialties: ["addiction", "alcohol-use-disorder", "substance-use", "depression", "co-occurring"],
    outcomeData: {
      addiction: { successRate: 79, caseCount: 212 },
      "alcohol-use-disorder": { successRate: 81, caseCount: 167 },
      "substance-use": { successRate: 77, caseCount: 143 },
      depression: { successRate: 74, caseCount: 99 },
    },
  },
  {
    name: "Dr. Amara Diallo",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Psychologist, Ph.D",
    location: "Washington, D.C.",
    bio: "Specializing in racial trauma, race-based stress, and the mental health impact of systemic racism for BIPOC adults and professionals.",
    languages: ["English", "French", "Wolof"],
    modalities: ["racial trauma therapy", "CBT", "ACT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["DC", "MD", "VA"],
    availability: {
      summary: "Open to BIPOC clients — RBST-informed practice",
      nextOpenSlot: "2026-04-24T13:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      culturalCompetency: ["BIPOC", "Black mental health", "African diaspora"],
    },
    specialties: ["anxiety", "depression", "trauma", "identity", "stress"],
    outcomeData: {
      anxiety: { successRate: 86, caseCount: 138 },
      depression: { successRate: 84, caseCount: 117 },
      trauma: { successRate: 87, caseCount: 99 },
      identity: { successRate: 91, caseCount: 88 },
    },
  },
  {
    name: "Patrick Nguyen, LMFT",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Marriage and Family Therapist",
    location: "San Jose, California",
    bio: "Second-generation immigrant experience, intergenerational family dynamics, and academic/career pressure for Southeast Asian adults.",
    languages: ["English", "Vietnamese"],
    modalities: ["family systems", "CBT", "narrative therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["CA"],
    availability: {
      summary: "Bilingual Vietnamese sessions available",
      nextOpenSlot: "2026-04-23T16:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "young-adults", "families"],
      culturalCompetency: ["Vietnamese diaspora", "Southeast Asian", "immigrant"],
    },
    specialties: ["family-conflict", "identity", "anxiety", "depression", "immigration-stress"],
    outcomeData: {
      "family-conflict": { successRate: 85, caseCount: 99 },
      identity: { successRate: 88, caseCount: 82 },
      anxiety: { successRate: 82, caseCount: 111 },
      "immigration-stress": { successRate: 87, caseCount: 71 },
    },
  },
  {
    name: "Dr. Nadia Petrova",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Psychologist, Psy.D",
    location: "New York, New York",
    bio: "Schema therapy and EMDR for adults with complex trauma histories, chronic shame, and deeply rooted self-critical patterns.",
    languages: ["English", "Russian"],
    modalities: ["schema therapy", "EMDR", "compassion-focused therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["NY", "NJ"],
    availability: {
      summary: "Open for complex trauma referrals",
      nextOpenSlot: "2026-04-25T10:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      traumaInformed: true,
      culturalCompetency: ["Eastern European diaspora"],
    },
    specialties: ["complex-ptsd", "trauma", "depression", "shame", "anxiety"],
    outcomeData: {
      "complex-ptsd": { successRate: 86, caseCount: 131 },
      trauma: { successRate: 83, caseCount: 107 },
      depression: { successRate: 80, caseCount: 122 },
      anxiety: { successRate: 77, caseCount: 98 },
    },
  },
  {
    name: "Dr. Theo Osei",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "ADHD Specialist, Ph.D",
    location: "Dallas, Texas",
    bio: "Cognitive rehabilitation and skills coaching for adults with ADHD, ASD, and executive function challenges — including late diagnosis.",
    languages: ["English"],
    modalities: ["CBT for ADHD", "cognitive rehabilitation", "psychoeducation"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["TX", "OK"],
    availability: {
      summary: "Open for ADHD assessments — adult specialization",
      nextOpenSlot: "2026-04-24T10:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "young-adults"],
      specialization: "adhd",
      assessments: true,
    },
    specialties: ["adhd", "executive-dysfunction", "anxiety", "depression", "procrastination"],
    outcomeData: {
      adhd: { successRate: 83, caseCount: 187 },
      "executive-dysfunction": { successRate: 80, caseCount: 144 },
      anxiety: { successRate: 76, caseCount: 108 },
      depression: { successRate: 73, caseCount: 88 },
    },
  },
  {
    name: "Rachel Kim, LCSW",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Clinical Social Worker",
    location: "Los Angeles, California",
    bio: "Trauma-informed LGBTQ+ affirmative therapy for queer and trans adults dealing with family estrangement, dysphoria, and transition stress.",
    languages: ["English", "Korean"],
    modalities: ["affirmative therapy", "IFS", "somatic experiencing"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["CA"],
    availability: {
      summary: "Open to queer and trans clients",
      nextOpenSlot: "2026-04-21T17:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "young-adults", "LGBTQ+"],
      lgbtqAffirming: true,
      transAffirming: true,
    },
    specialties: ["lgbtq", "identity", "trauma", "anxiety", "depression"],
    outcomeData: {
      lgbtq: { successRate: 92, caseCount: 166 },
      identity: { successRate: 90, caseCount: 144 },
      trauma: { successRate: 83, caseCount: 98 },
      anxiety: { successRate: 80, caseCount: 121 },
    },
  },
  {
    name: "Dr. Carlos Mendez",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Psychologist, Ph.D",
    location: "El Paso, Texas",
    bio: "Bilingual CBT and trauma therapy for border community adults navigating displacement trauma, family separation, and chronic stress.",
    languages: ["English", "Spanish"],
    modalities: ["trauma-focused CBT", "narrative therapy", "EMDR"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["TX", "NM"],
    availability: {
      summary: "Accepting bilingual Spanish-English trauma clients",
      nextOpenSlot: "2026-04-23T14:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "families"],
      culturalCompetency: ["Latinx", "border communities", "immigrant"],
    },
    specialties: ["trauma", "ptsd", "depression", "anxiety", "immigration-stress"],
    outcomeData: {
      trauma: { successRate: 85, caseCount: 121 },
      ptsd: { successRate: 82, caseCount: 99 },
      depression: { successRate: 80, caseCount: 111 },
      anxiety: { successRate: 82, caseCount: 104 },
    },
  },
  {
    name: "Hannah Clarke, LPC",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Professional Counselor",
    location: "Austin, Texas",
    bio: "ACT and values-based therapy for young adults in career transitions, identity fog, and the quarter-life crisis of figuring out what matters.",
    languages: ["English"],
    modalities: ["ACT", "solution-focused", "narrative therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["TX", "CO"],
    availability: {
      summary: "Open to young adult life transitions clients",
      nextOpenSlot: "2026-04-22T13:00:00.000Z",
    },
    profileAttributes: { populations: ["young-adults"] },
    specialties: ["life-transitions", "identity", "anxiety", "depression", "self-esteem"],
    outcomeData: {
      "life-transitions": { successRate: 89, caseCount: 154 },
      identity: { successRate: 86, caseCount: 121 },
      anxiety: { successRate: 83, caseCount: 138 },
      depression: { successRate: 80, caseCount: 101 },
    },
  },
  {
    name: "Dr. Femi Adeyemi",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Neuropsychologist, Ph.D",
    location: "Baltimore, Maryland",
    bio: "Neuropsychological evaluation and treatment for ADHD, learning disabilities, and cognitive challenges related to depression and chronic illness.",
    languages: ["English", "Yoruba"],
    modalities: ["neuropsychological assessment", "CBT", "cognitive rehabilitation"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["MD", "VA", "DC"],
    availability: {
      summary: "Accepting neuropsychological assessments and ADHD evaluations",
      nextOpenSlot: "2026-04-28T09:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      assessments: true,
      specialization: "neuropsychology",
    },
    specialties: ["adhd", "executive-dysfunction", "depression", "anxiety", "cognitive-difficulties"],
    outcomeData: {
      adhd: { successRate: 84, caseCount: 177 },
      "executive-dysfunction": { successRate: 81, caseCount: 133 },
      depression: { successRate: 77, caseCount: 99 },
    },
  },
  {
    name: "Dr. Elizabeth Marsh",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Psychologist, Ph.D",
    location: "San Diego, California",
    bio: "Integrated mind-body approach for chronic pain, somatic symptoms, and medically unexplained symptoms. Trained in pain psychology and health psychology.",
    languages: ["English"],
    modalities: ["pain psychology", "ACT", "mindfulness-based stress reduction"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["CA", "AZ"],
    availability: {
      summary: "Open for chronic pain and somatic health clients",
      nextOpenSlot: "2026-04-24T11:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      specialization: "health-psychology",
    },
    specialties: ["chronic-pain", "somatic", "anxiety", "depression", "burnout"],
    outcomeData: {
      "chronic-pain": { successRate: 82, caseCount: 143 },
      somatic: { successRate: 79, caseCount: 88 },
      anxiety: { successRate: 81, caseCount: 122 },
      depression: { successRate: 77, caseCount: 104 },
    },
  },
  {
    name: "James Okafor, LPC",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Professional Counselor",
    location: "Columbus, Ohio",
    bio: "Motivational and strengths-based therapy for adults dealing with stagnation, procrastination, and the gap between where they are and where they want to be.",
    languages: ["English"],
    modalities: ["motivational interviewing", "solution-focused", "CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["OH", "KY", "IN"],
    availability: {
      summary: "Multiple openings — accepting new clients",
      nextOpenSlot: "2026-04-21T09:00:00.000Z",
    },
    profileAttributes: { populations: ["adults", "young-adults"] },
    specialties: ["depression", "anxiety", "life-transitions", "self-esteem", "burnout"],
    outcomeData: {
      depression: { successRate: 82, caseCount: 164 },
      anxiety: { successRate: 80, caseCount: 149 },
      "life-transitions": { successRate: 86, caseCount: 117 },
      burnout: { successRate: 79, caseCount: 98 },
    },
  },
  {
    name: "Dr. Nalini Patel",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Psychologist, Psy.D",
    location: "Chicago, Illinois",
    bio: "Mindfulness-based and somatic therapy for generalized anxiety, social anxiety, and stress-related physical symptoms in professionals.",
    languages: ["English", "Gujarati", "Hindi"],
    modalities: ["MBCT", "somatic experiencing", "CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["IL", "IN"],
    availability: {
      summary: "Open to anxiety and stress clients — trilingual practice",
      nextOpenSlot: "2026-04-22T12:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "professionals"],
      culturalCompetency: ["South Asian", "Indian diaspora"],
    },
    specialties: ["anxiety", "stress", "depression", "burnout", "perfectionism"],
    outcomeData: {
      anxiety: { successRate: 88, caseCount: 201 },
      stress: { successRate: 90, caseCount: 177 },
      burnout: { successRate: 85, caseCount: 143 },
      depression: { successRate: 82, caseCount: 121 },
    },
  },
  {
    name: "Dr. Brendan Walsh",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Psychologist, Ph.D",
    location: "Boston, Massachusetts",
    bio: "Psychodynamic and relational therapy for men navigating depression, emotional avoidance, and the unspoken costs of stoicism.",
    languages: ["English"],
    modalities: ["psychodynamic", "relational therapy", "CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["MA", "RI", "CT"],
    availability: {
      summary: "Open to male clients — depression and identity focus",
      nextOpenSlot: "2026-04-25T14:00:00.000Z",
    },
    profileAttributes: { populations: ["adults"], specialization: "men-mental-health" },
    specialties: ["depression", "anxiety", "identity", "relationship-issues", "burnout"],
    outcomeData: {
      depression: { successRate: 86, caseCount: 188 },
      anxiety: { successRate: 82, caseCount: 156 },
      identity: { successRate: 84, caseCount: 109 },
      "relationship-issues": { successRate: 79, caseCount: 88 },
    },
  },
  {
    name: "Celeste Moreau, LCSW",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Clinical Social Worker",
    location: "New York, New York",
    bio: "Parts-based and somatic therapy for women with complex trauma, chronic dissociation, and histories of neglect or emotional abuse.",
    languages: ["English", "French"],
    modalities: ["IFS", "somatic experiencing", "trauma-focused CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["NY", "CT", "NJ"],
    availability: {
      summary: "Accepting complex trauma referrals for women",
      nextOpenSlot: "2026-04-23T11:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "women"],
      traumaInformed: true,
    },
    specialties: ["complex-ptsd", "trauma", "dissociation", "depression", "anxiety"],
    outcomeData: {
      "complex-ptsd": { successRate: 87, caseCount: 121 },
      trauma: { successRate: 84, caseCount: 99 },
      dissociation: { successRate: 80, caseCount: 67 },
      depression: { successRate: 78, caseCount: 104 },
    },
  },
  {
    name: "Dr. Aisha Coleman",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Psychiatrist, MD",
    location: "Houston, Texas",
    bio: "Reproductive psychiatry and women's mental health — specialist in perimenopause, premenstrual dysphoric disorder, and perinatal psychiatry.",
    languages: ["English"],
    modalities: ["reproductive psychiatry", "CBT", "psychoeducation"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["TX", "LA", "OK"],
    availability: {
      summary: "Accepting women's mental health referrals",
      nextOpenSlot: "2026-04-26T10:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "women", "perinatal"],
      prescribes: true,
      specialization: "reproductive-psychiatry",
    },
    specialties: ["postpartum-depression", "depression", "anxiety", "pmdd", "burnout"],
    outcomeData: {
      "postpartum-depression": { successRate: 89, caseCount: 144 },
      depression: { successRate: 85, caseCount: 188 },
      anxiety: { successRate: 81, caseCount: 144 },
      pmdd: { successRate: 84, caseCount: 77 },
    },
  },
  {
    name: "Noah Abrams, LPC",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Professional Counselor",
    location: "Las Vegas, Nevada",
    bio: "Spirituality-integrated therapy for individuals navigating existential crisis, loss of faith, moral injury, and meaning-making after trauma.",
    languages: ["English", "Hebrew"],
    modalities: ["existential therapy", "meaning-centered therapy", "ACT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["NV", "AZ", "CA"],
    availability: {
      summary: "Open to meaning-focused and existential clients",
      nextOpenSlot: "2026-04-24T16:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      spirituallyIntegrated: true,
    },
    specialties: ["identity", "grief", "depression", "anxiety", "life-transitions"],
    outcomeData: {
      identity: { successRate: 87, caseCount: 112 },
      grief: { successRate: 85, caseCount: 97 },
      depression: { successRate: 82, caseCount: 133 },
      "life-transitions": { successRate: 88, caseCount: 109 },
    },
  },
  {
    name: "Dr. Ingrid Larson",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Psychologist, Ph.D",
    location: "Minneapolis, Minnesota",
    bio: "Dialectical behavior therapy for borderline personality, emotional dysregulation, and chronic suicidality. Trained in DBT-PE for trauma.",
    languages: ["English", "Swedish"],
    modalities: ["DBT", "DBT-PE", "CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["MN", "WI", "ND"],
    availability: {
      summary: "Accepting DBT referrals — individual and skills group",
      nextOpenSlot: "2026-04-27T10:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "young-adults"],
      specialization: "DBT",
    },
    specialties: ["borderline-personality", "emotional-dysregulation", "depression", "trauma", "anxiety"],
    outcomeData: {
      "borderline-personality": { successRate: 81, caseCount: 122 },
      "emotional-dysregulation": { successRate: 85, caseCount: 144 },
      depression: { successRate: 80, caseCount: 138 },
      trauma: { successRate: 77, caseCount: 88 },
    },
  },
  {
    name: "Dr. Emmanuel Adaora",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Psychologist, Ph.D",
    location: "San Diego, California",
    bio: "Military and veteran-focused trauma therapy using prolonged exposure, CPT, and peer-supported recovery models.",
    languages: ["English", "Igbo"],
    modalities: ["prolonged exposure", "CPT", "CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["CA", "TX", "VA"],
    availability: {
      summary: "Accepting veteran and active-duty referrals",
      nextOpenSlot: "2026-04-23T08:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "veterans"],
      militaryExpertise: true,
    },
    specialties: ["ptsd", "complex-ptsd", "depression", "anxiety", "moral-injury"],
    outcomeData: {
      ptsd: { successRate: 88, caseCount: 201 },
      "complex-ptsd": { successRate: 84, caseCount: 144 },
      depression: { successRate: 80, caseCount: 167 },
      "moral-injury": { successRate: 83, caseCount: 88 },
    },
  },
  {
    name: "Carmen Vega, LMFT",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Marriage and Family Therapist",
    location: "Miami, Florida",
    bio: "Intergenerational family therapy and couples work for Latinx families navigating migration, assimilation stress, and cultural identity conflicts.",
    languages: ["English", "Spanish", "Portuguese"],
    modalities: ["EFT", "family systems", "culturally-adapted CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["FL", "NY", "TX"],
    availability: {
      summary: "Trilingual sessions — English, Spanish, Portuguese",
      nextOpenSlot: "2026-04-22T11:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "couples", "families"],
      culturalCompetency: ["Latinx", "Brazilian", "Caribbean"],
    },
    specialties: ["family-conflict", "relationship-issues", "immigration-stress", "identity", "anxiety"],
    outcomeData: {
      "family-conflict": { successRate: 87, caseCount: 133 },
      "relationship-issues": { successRate: 84, caseCount: 118 },
      "immigration-stress": { successRate: 88, caseCount: 77 },
      anxiety: { successRate: 81, caseCount: 104 },
    },
  },
  {
    name: "Dr. Michelle Tran",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Psychologist, Psy.D",
    location: "San Jose, California",
    bio: "Culturally grounded therapy for Asian American adults navigating model minority stress, family obligation, and the silence around mental health.",
    languages: ["English", "Vietnamese", "Mandarin"],
    modalities: ["CBT", "ACT", "culturally-adapted therapy"],
    careFormats: ["virtual"],
    licensedStates: ["CA", "WA"],
    availability: {
      summary: "Virtual sessions available — multilingual practice",
      nextOpenSlot: "2026-04-25T09:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "young-adults"],
      culturalCompetency: ["Asian American", "Southeast Asian", "East Asian"],
    },
    specialties: ["anxiety", "depression", "identity", "burnout", "family-conflict"],
    outcomeData: {
      anxiety: { successRate: 86, caseCount: 156 },
      depression: { successRate: 83, caseCount: 133 },
      identity: { successRate: 89, caseCount: 111 },
      burnout: { successRate: 82, caseCount: 98 },
    },
  },
  {
    name: "Dr. Oliver Patterson",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Psychologist, Ph.D",
    location: "Denver, Colorado",
    bio: "Adventure therapy and CBT integration for anxiety, depression, and life purpose — especially for outdoor professionals and athletes.",
    languages: ["English"],
    modalities: ["CBT", "adventure therapy", "ACT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["CO", "UT", "WY"],
    availability: {
      summary: "Open for outdoor-lifestyle and athlete mental health",
      nextOpenSlot: "2026-04-24T08:00:00.000Z",
    },
    profileAttributes: { populations: ["adults", "athletes"] },
    specialties: ["anxiety", "depression", "identity", "life-transitions", "burnout"],
    outcomeData: {
      anxiety: { successRate: 85, caseCount: 144 },
      depression: { successRate: 83, caseCount: 127 },
      "life-transitions": { successRate: 87, caseCount: 109 },
      burnout: { successRate: 84, caseCount: 98 },
    },
  },
  {
    name: "Grace Oduya, LCSW",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Clinical Social Worker",
    location: "Charlotte, North Carolina",
    bio: "Trauma-centered grief therapy for adults who experienced traumatic bereavement — homicide loss, overdose deaths, suicide loss survivors.",
    languages: ["English"],
    modalities: ["trauma-focused CBT", "complicated grief treatment", "supportive therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["NC", "SC", "GA"],
    availability: {
      summary: "Accepting traumatic loss and grief referrals",
      nextOpenSlot: "2026-04-25T11:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      traumaInformed: true,
    },
    specialties: ["grief", "trauma", "complex-grief", "depression", "ptsd"],
    outcomeData: {
      grief: { successRate: 88, caseCount: 122 },
      trauma: { successRate: 84, caseCount: 99 },
      "complex-grief": { successRate: 86, caseCount: 77 },
      depression: { successRate: 80, caseCount: 104 },
    },
  },
  {
    name: "Dr. Sanjay Mehta",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Psychiatrist, MD",
    location: "New York, New York",
    bio: "Psychopharmacology-focused practice for treatment-resistant mood disorders, OCD, and anxiety — integrating cutting-edge protocols including ketamine consultation.",
    languages: ["English", "Hindi"],
    modalities: ["integrative psychiatry", "TMS consultation", "CBT-informed psychopharmacology"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["NY", "NJ", "CT"],
    availability: {
      summary: "Accepting psychiatric referrals for treatment-resistant cases",
      nextOpenSlot: "2026-05-01T10:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      prescribes: true,
      specialization: "treatment-resistant",
    },
    specialties: ["depression", "treatment-resistant-depression", "ocd", "anxiety", "bipolar-disorder"],
    outcomeData: {
      "treatment-resistant-depression": { successRate: 78, caseCount: 111 },
      depression: { successRate: 86, caseCount: 243 },
      ocd: { successRate: 82, caseCount: 133 },
      anxiety: { successRate: 80, caseCount: 177 },
    },
  },
  {
    name: "Vanessa Osei-Kuffour, LMFT",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Marriage and Family Therapist",
    location: "Atlanta, Georgia",
    bio: "Relationship therapy for Black couples and individuals addressing communication, intimacy, and the cultural narratives that shape partnership.",
    languages: ["English", "Twi"],
    modalities: ["EFT", "Gottman Method", "culturally-adapted therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["GA", "FL", "SC"],
    availability: {
      summary: "Open for couples and relationship therapy",
      nextOpenSlot: "2026-04-22T18:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "couples"],
      culturalCompetency: ["Black mental health", "Ghanaian diaspora"],
    },
    specialties: ["relationship-issues", "attachment", "anxiety", "depression", "identity"],
    outcomeData: {
      "relationship-issues": { successRate: 88, caseCount: 154 },
      attachment: { successRate: 85, caseCount: 112 },
      anxiety: { successRate: 80, caseCount: 99 },
      depression: { successRate: 78, caseCount: 88 },
    },
  },
  {
    name: "Dr. Lydia Svensson",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Psychologist, Ph.D",
    location: "Portland, Oregon",
    bio: "Somatic and IFS therapy for anxiety, hypervigilance, and the body-stored residues of prolonged stress and early attachment disruption.",
    languages: ["English", "Swedish"],
    modalities: ["IFS", "somatic experiencing", "polyvagal-informed therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["OR", "WA"],
    availability: {
      summary: "Open for somatic and nervous system-focused therapy",
      nextOpenSlot: "2026-04-23T15:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      traumaInformed: true,
    },
    specialties: ["anxiety", "hypervigilance", "trauma", "complex-ptsd", "burnout"],
    outcomeData: {
      anxiety: { successRate: 87, caseCount: 167 },
      hypervigilance: { successRate: 84, caseCount: 99 },
      trauma: { successRate: 82, caseCount: 121 },
      "complex-ptsd": { successRate: 85, caseCount: 109 },
    },
  },
  {
    name: "Thomas Achebe, LPC",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Professional Counselor",
    location: "Phoenix, Arizona",
    bio: "Strength-based therapy for young adults navigating LGBTQ+ identity, religious identity conflicts, and coming out in conservative family environments.",
    languages: ["English"],
    modalities: ["affirmative therapy", "narrative therapy", "ACT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["AZ", "NM", "TX"],
    availability: {
      summary: "Affirming therapy for LGBTQ+ young adults",
      nextOpenSlot: "2026-04-24T13:00:00.000Z",
    },
    profileAttributes: {
      populations: ["young-adults", "LGBTQ+"],
      lgbtqAffirming: true,
    },
    specialties: ["lgbtq", "identity", "anxiety", "depression", "family-conflict"],
    outcomeData: {
      lgbtq: { successRate: 89, caseCount: 134 },
      identity: { successRate: 88, caseCount: 122 },
      anxiety: { successRate: 83, caseCount: 108 },
      depression: { successRate: 80, caseCount: 97 },
    },
  },
  {
    name: "Dr. Susan MacLeod",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Clinical Psychologist, Ph.D",
    location: "Chicago, Illinois",
    bio: "Health psychology and chronic illness coping — specialized in the emotional impact of cancer, autoimmune disease, and medically complex diagnoses.",
    languages: ["English"],
    modalities: ["acceptance and commitment therapy", "health psychology", "CBT"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["IL", "IN", "WI"],
    availability: {
      summary: "Accepting health psychology and chronic illness referrals",
      nextOpenSlot: "2026-04-25T13:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults"],
      specialization: "health-psychology",
    },
    specialties: ["chronic-illness", "depression", "anxiety", "grief", "life-transitions"],
    outcomeData: {
      "chronic-illness": { successRate: 85, caseCount: 122 },
      depression: { successRate: 82, caseCount: 167 },
      anxiety: { successRate: 80, caseCount: 144 },
      grief: { successRate: 83, caseCount: 88 },
    },
  },
  {
    name: "Andre Beaumont, LCSW",
    providerType: "mental-health",
    networkSource: "anamnesis-core",
    title: "Licensed Clinical Social Worker",
    location: "New Orleans, Louisiana",
    bio: "Intergenerational trauma and community resilience work for Black and Native families affected by historical trauma, displacement, and grief.",
    languages: ["English"],
    modalities: ["culturally-adapted therapy", "trauma-focused CBT", "narrative therapy"],
    careFormats: ["virtual", "in-person"],
    licensedStates: ["LA", "MS", "TX"],
    availability: {
      summary: "Open to cultural trauma and intergenerational work",
      nextOpenSlot: "2026-04-23T10:00:00.000Z",
    },
    profileAttributes: {
      populations: ["adults", "families"],
      culturalCompetency: ["Black mental health", "Indigenous trauma"],
    },
    specialties: ["trauma", "depression", "grief", "identity", "complex-ptsd"],
    outcomeData: {
      trauma: { successRate: 84, caseCount: 111 },
      depression: { successRate: 81, caseCount: 133 },
      grief: { successRate: 83, caseCount: 88 },
      identity: { successRate: 86, caseCount: 77 },
    },
  },
];

export function getTherapistAccountByName(name: string): TherapistAccountSeed | undefined {
  return therapistRoster.find(
    (t) => t.name.toLowerCase() === name.toLowerCase()
  );
}

export function getTherapistAccountByEmail(email: string): TherapistAccountSeed | undefined {
  return therapistRoster.find(
    (t) => t.email?.toLowerCase() === email.toLowerCase()
  );
}
